In [69]:
import pandas as pd

In [70]:
emissions = pd.read_csv("emission data.csv")
emissions.head()

,Country,1751,1752,1753,1754,1755,1756,1757,1758,1759,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Afghanistan,0,0,0,0,0,0,0,0,0,...,8.515264e+07,9.191295e+07,1.003652e+08,1.125912e+08,1.233332e+08,1.333337e+08,1.431228e+08,1.532303e+08,1.654882e+08,1.785029e+08
1,Africa,0,0,0,0,0,0,0,0,0,...,3.183077e+10,3.301904e+10,3.421283e+10,3.541120e+10,3.664504e+10,3.789569e+10,3.918617e+10,4.047518e+10,4.178583e+10,4.311757e+10
2,Albania,0,0,0,0,0,0,0,0,0,...,2.287948e+08,2.331696e+08,2.377643e+08,2.430001e+08,2.479062e+08,2.529662e+08,2.586784e+08,2.646261e+08,2.708990e+08,2.772782e+08
3,Algeria,0,0,0,0,0,0,0,0,0,...,2.894820e+09,3.015005e+09,3.132819e+09,3.252626e+09,3.380736e+09,3.513171e+09,3.656348e+09,3.806940e+09,3.957319e+09,4.107870e+09
4,Americas (other),0,0,0,0,0,0,0,0,0,...,7.746025e+10,7.961787e+10,8.187178e+10,8.416656e+10,8.654197e+10,8.894874e+10,9.139192e+10,9.382747e+10,9.624253e+10,9.864116e+10

In [71]:
#Melt the columns into rows
emissions_df = pd.melt(emissions, id_vars=["Country"], 
                  var_name="year", value_name="GHG")

emissions_df["Country"] = emissions_df["Country"].str.upper()
emissions_df["year"] = emissions_df["year"].astype(int)

emissions_df.head()

            Country  year  GHG
0       AFGHANISTAN  1751  0.0
1            AFRICA  1751  0.0
2           ALBANIA  1751  0.0
3           ALGERIA  1751  0.0
4  AMERICAS (OTHER)  1751  0.0

In [ ]:
temp_df = pd.read_csv("GlobalLandTemperaturesByCountry_clean.csv").drop("Unnamed: 0", axis = 1)

temp_df["Country"] = temp_df["Country"].astype(str)
temp_df["year"] = temp_df["year"].astype(int)

temp_df.head()

### Merge the two datasets by country and year

In [78]:
df = pd.merge(temp_df,emissions_df,on=["Country","year"],how="left")
df.tail(50)

,dt,AverageTemperature,AverageTemperatureUncertainty,Country,year,country_code,continent,Latitude,Longitude,GHG
505926,2009-08-01,18.465,0.489,ZIMBABWE,2009,ZW,AF,-20.0,30.0,622611834.0
505927,2009-09-01,22.831,0.329,ZIMBABWE,2009,ZW,AF,-20.0,30.0,622611834.0
505928,2009-10-01,24.544,0.429,ZIMBABWE,2009,ZW,AF,-20.0,30.0,622611834.0
505929,2009-11-01,23.886,0.421,ZIMBABWE,2009,ZW,AF,-20.0,30.0,622611834.0
505930,2009-12-01,24.731,0.430,ZIMBABWE,2009,ZW,AF,-20.0,30.0,622611834.0
505931,2010-01-01,24.660,0.459,ZIMBABWE,2010,ZW,AF,-20.0,30.0,630292845.0
505932,2010-02-01,24.297,0.565,ZIMBABWE,2010,ZW,AF,-20.0,30.0,630292845.0
505933,2010-03-01,23.499,0.249,ZIMBABWE,2010,ZW,AF,-20.0,30.0,630292845.0
505934,2010-04-01,21.907,0.293,ZIMBABWE,2010,ZW,AF,-20.0,30.0,630292845.0
505935,2010-05-01,20.147,0.534,ZIMBABWE,2010,ZW,AF,-20.0,30.0,630292845.0
505936,2010-06-01,16.377,0.476,ZIMBABWE,2010,ZW,AF,-20.0,30.0,630292845.0
505937,2010-07-01,16.668,0.410,ZIMBABWE,2010,ZW,AF,-20.0,30.0,630292845.0
505938,2010-08-01,18.260,0.447,ZIMBABWE,2010,ZW,AF,-20.0,30.0,630292845.0
505939,2010-09-01,23.109,0.225,ZIMBABWE,2010,ZW,AF,-20.0,30.0,630292845.0
505940,2010-10-01,25.943,0.369,ZIMBABWE,2010,ZW,AF,-20.0,30.0,630292845.0
505941,2010-11-01,25.211,0.356,ZIMBABWE,2010,ZW,AF,-20.0,30.0,630292845.0
505942,2010-12-01,23.757,0.533,ZIMBABWE,2010,ZW,AF,-20.0,30.0,630292845.0
505943,2011-01-01,22.982,0.460,ZIMBABWE,2011,ZW,AF,-20.0,30.0,639732696.0
505944,2011-02-01,23.166,0.260,ZIMBABWE,2011,ZW,AF,-20.0,30.0,639732696.0
505945,2011-03-01,23.668,0.183,ZIMBABWE,2011,ZW,AF,-20.0,30.0,639732696.0
505946,2011-04-01,21.759,0.319,ZIMBABWE,2011,ZW,AF,-20.0,30.0,639732696.0
505947,2011-05-01,19.627,0.398,ZIMBABWE,2011,ZW,AF,-20.0,30.0,639732696.0
505948,2011-06-01,16.939,0.599,ZIMBABWE,2011,ZW,AF,-20.0,30.0,639732696.0
505949,2011-07-01,15.803,0.447,ZIMBABWE,2011,ZW,AF,-20.0,30.0,639732696.0
505950,2011-08-01,17.883,0.328,ZIMBABWE,2011,ZW,AF,-20.0,30.0,639732696.0
505951,2011-09-01,22.902,0.612,ZIMBABWE,2011,ZW,AF,-20.0,30.0,639732696.0
505952,2011-10-01,24.966,0.441,ZIMBABWE,2011,ZW,AF,-20.0,30.0,639732696.0
505953,2011-11-01,25.521,0.318,ZIMBABWE,2011,ZW,AF,-20.0,30.0,639732696.0
505954,2011-12-01,24.013,0.356,ZIMBABWE,2011,ZW,AF,-20.0,30.0,639732696.0
505955,2012-01-01,23.872,0.247,ZIMBABWE,2012,ZW,AF,-20.0,30.0,647347296.0
505956,2012-02-01,24.294,0.305,ZIMBABWE,2012,ZW,AF,-20.0,30.0,647347296.0
505957,2012-03-01,23.596,0.354,ZIMBABWE,2012,ZW,AF,-20.0,30.0,647347296.0
505958,2012-04-01,20.349,0.462,ZIMBABWE,2012,ZW,AF,-20.0,30.0,647347296.0
505959,2012-05-01,19.712,0.312,ZIMBABWE,2012,ZW,AF,-20.0,30.0,647347296.0
505960,2012-06-01,16.631,0.277,ZIMBABWE,2012,ZW,AF,-20.0,30.0,647347296.0
505961,2012-07-01,16.048,0.783,ZIMBABWE,2012,ZW,AF,-20.0,30.0,647347296.0
505962,2012-08-01,18.946,1.127,ZIMBABWE,2012,ZW,AF,-20.0,30.0,647347296.0
505963,2012-09-01,22.609,0.643,ZIMBABWE,2012,ZW,AF,-20.0,30.0,647347296.0
505964,2012-10-01,23.482,0.574,ZIMBABWE,2012,ZW,AF,-20.0,30.0,647347296.0
505965,2012-11-01,24.606,0.532,ZIMBABWE,2012,ZW,AF,-20.0,30.0,647347296.0
505966,2012-12-01,24.111,0.846,ZIMBABWE,2012,ZW,AF,-20.0,30.0,647347296.0
505967,2013-01-01,23.812,1.218,ZIMBABWE,2013,ZW,AF,-20.0,30.0,658883535.0
505968,2013-02-01,24.075,1.286,ZIMBABWE,2013,ZW,AF,-20.0,30.0,658883535.0
505969,2013-03-01,23.226,0.564,ZIMBABWE,2013,ZW,AF,-20.0,30.0,658883535.0
505970,2013-04-01,21.142,0.495,ZIMBABWE,2013,ZW,AF,-20.0,30.0,658883535.0
505971,2013-05-01,19.059,1.022,ZIMBABWE,2013,ZW,AF,-20.0,30.0,658883535.0
505972,2013-06-01,17.613,0.473,ZIMBABWE,2013,ZW,AF,-20.0,30.0,658883535.0
505973,2013-07-01,17.000,0.453,ZIMBABWE,2013,ZW,AF,-20.0,30.0,658883535.0
505974,2013-08-01,19.759,0.717,ZIMBABWE,2013,ZW,AF,-20.0,30.0,658883535.0
505975,2013-09-01,NaN,NaN,ZIMBABWE,2013,ZW,AF,-20.0,30.0,658883535.0

### Export data

In [ ]:
df.to_csv("GlobalLandTemperaturesByCountry+GHG")